export const SET_DIALOGS_ITEMS = 'SET_DIALOGS_ITEMS';
export const SET_CURRENT_DIALOG_ID = 'SET_CURRENT_DIALOG_ID';

export const SET_MESSAGES_ITEMS = 'SET_MESSAGES_ITEMS';
export const SET_MESSAGES_IS_LOADING = 'SET_MESSAGES_IS_LOADING';
export const SET_NEW_MESSAGE = 'SET_NEW_MESSAGE';

export const SET_USER_DATA = 'SET_USER_DATA';
export const SET_USER_LOGOUT = 'SET_USER_LOGOUT';

export const SET_ATTACHMENTS_DATA = 'SET_ATTACHMENTS_DATA';
export const REMOVE_ATTACHMENTS_DATA = 'REMOVE_ATTACHMENTS_DATA';





